### ISSUE TITLE
These files are labeled as IBM Confidential, and are not open source. If they are mis-labeled you should update the file headers, otherwise they should not be used and must be removed from your repository.

### ISSUE THREAD

**Issue by ryjones** [hyperledger-labs/fabric-operator#109]
[This files are labeled as IBM Confidential, and are not open source. If they are mis-labeled you should update the file headers, otherwise they should not be used and must be removed from your repository.](https://github.com/hyperledger-labs/fabric-operator/blob/282ca83c4c3fc3ac013609737a638ec6b7013d6c/sample-network-multi-org/scripts/kind_with_nginx.sh#L4-L12)

**Comment by asararatnakar** [comment]
@ryjones Thank you.
Yes that seems like it was an accidental commit. We have updated the licenses wherever applicable.

**Comment by ryjones** [comment]
thank you!
