### ISSUE TITLE
Make the UseTags Flag Default to true

### ISSUE THREAD

**Issue by shoaebjindani** [hyperledger-labs/fabric-operator#148]
Operator code checks **UseTags** flag to [decide](https://github.com/hyperledger-labs/fabric-operator/blob/main/pkg/offering/base/console/override/deployment.go#L173
) a switch between docker image Tags and Digests.
Proposing to set the flag **useTags** to a default value **True** in the code, To avoid explicit mention of this flag  in the Console CR (Custome Resource) Spec

**Comment by asararatnakar** [comment]
This is done. Closing
