### ISSUE TITLE
Implement / Validate k509 certificate auto-renewal features

### ISSUE THREAD

**Issue by jkneubuh** [hyperledger-labs/fabric-operator#34]
There are some partial hooks to run, test, and validate an x509 certificate "auto-renewal" feature in the operator.

Turn this feature on, and keep it on forever.

Certificate expiry / recovery has been the bane, and doomed, many a blockchain network. 

This feature should be re-named:   "disarm the Fabric certificate time bomb."   

This has to change.  It is not good for _anyone_ when certificates expire, en masse, and a network loses consensus at the orderers.

**Comment by jkneubuh** [comment]
cc: @celder @asararatnakar @yacovm

**Comment by yacovm** [comment]
How does it work though? Suppose a TLS certificate expires, or an enrollment certificate expires. How do you replace the node's certificate without restarting the node? Do you restart the node automatically?

**Comment by yacovm** [comment]
And what if it's a root CA certificate?

**Comment by yacovm** [comment]
Keep in mind that if you restart a Raft orderer and it's the leader, you will have an outage until the rest of the orderers will elect a new leader.

**Comment by yacovm** [comment]
But I think that in Raft, what we can perhaps do, is make the leader orderer self examine the certificates of the rest of the nodes that are available, and if it sees its certificate is the closest to expire, to transfer its leadership to some other node. 
We do a similar thing when we remove the leader from the channel - it detects it and politely [steps down](https://github.com/hyperledger/fabric/blob/main/orderer/consensus/etcdraft/chain.go#L1123-L1124) from being the leader.

**Comment by bjwswang** [comment]
@jkneubuh Any update on this topic ? Does`fabric-operator` supports x509 certificte auto-renewal ?

**Comment by jkneubuh** [comment]
Hi @bjwswang - thanks for the follow up.   Yes, the current operator builds will fully support cert renewal.  

This landed in PR #40 - (thanks @asararatnakar !)
