### ISSUE TITLE
Issues with the new k8s.io v1.25.0 update

### ISSUE THREAD

**Issue by jkneubuh** [hyperledger-labs/fabric-operator#50]
K8s bumped from v1.24.x to v1.25 on August 1.

This is causing some issues that we started to notice when installing KIND clusters with the default kube rev pulled down by kind v1.15 (kube 1.25).

It's not clear how far the tendrils reach, but it looks like there are at a minimum a few deprecations / removals related to Pod Security Policies that are breaking the current builds of operator and sample network.

1.  Stabilize this by pinning the test / validation clusters used for dev (sample network KIND) and CI (gha executors) to run with k8s 1.24.   This just needs a new revision / label to be applied to the `kind create cluster ...` to hold water.

2.  Test with KIND / k8s 1.25, and start upgrading the removal/deprecated APIs as necessary.

**Comment by bjwswang** [comment]
Maybe we should version the config files. And allow customzie `K8S_CLUSTER_VERSION` or `K8S_CLUSTER_IMAGE`

**Comment by jkneubuh** [comment]
Thank you, @celder628 for the notes on the PSP upgrade: 

https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/


- implementation steps:

Add the following label to the operator namespace:

```
$ kubectl label --overwrite ns [namespace] pod-security.kubernetes.io/enforce=baseline
```

- Remove the following section from the IBP clusterrole:
```
- apiGroups:
  - extensions
  resourceNames:
  - ibm-hlfsupport-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
```
