### ISSUE TITLE
document typo `localho.st` which should be `localhost`

### ISSUE THREAD

**Issue by bjwswang** [hyperledger-labs/fabric-operator#62]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/30621793/197508223-72b8e8a6-abb0-4cb6-8944-6c823d827fbe.png">

Hi there, is this a typo ?

**Comment by jkneubuh** [comment]
Hi @bjwswang - `localho.st` is a special DNS wildcard domain that will match any host name with the localho.st suffix to 127.0.0.1.  So for instance, foo.localho.st -> 127.0.0.1, bar.localho.st -> 127.0.0.1, etc.  This is similar to registering a wildcard resolver with the [Dead simple wildcard DNS for any IP Address](https://nip.io) domain 127-0-0-1.nip.io.

By registering a *.localho.st domain with the Nginx ingress controller, all of the virtual Ingress routes created by the operator (e.g. org1-peer1-peer.localho.st, org1-peer2-peer.localho.st, etc.) will be directed into the cluster.

It looks a little funny, but is a LOT more convenient than configuring `dnsmasq` or manually editing /etc/hosts with the ingress host names.

**Comment by bjwswang** [comment]
@jkneubuh thanks.awesome design
