### ISSUE TITLE
unable to run operator in local due to hardcode settings

### ISSUE THREAD

**Issue by bjwswang** [hyperledger-labs/fabric-operator#67]
Running operator locally helps a lot on developement,but hardcode settings when start operator make it impossible. 
Here i summarized the hardcode settings and solution to make `run locally` works .
1. Add a new environment variable `OPERATOR_RUN_MODE`  to indicate run operator `local` or `cluster`.    
**Code to change**   
- pkg/command/operator: add `RunMode` and extract from environment variable
```
// RunMode indicates how operator is being deployed
type RunMode string

const (
	Local   RunMode = "local"
	Cluster RunMode = "cluster"
)

func RunInLocal() bool {
	return os.Getenv("OPERATOR_RUN_MODE") == string(Local)
}
```
- pkg/command/operator: read `local` from  `RunInLocal`
```
func Operator(operatorCfg *oconfig.Config, blocking bool) error {
	signalHandler := signals.SetupSignalHandler()
	return OperatorWithSignal(operatorCfg, signalHandler, blocking, RunInLocal()) 
}
```

2. Add a new environment variable `OPERAOTR_BASE_PATH` to indicate where to find `default config` and `default definitions`.   
**Code to change**  
- main.go:  read environment variable and reset `default config and default definitions`
```
func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
	utilruntime.Must(ibpv1beta1.AddToScheme(scheme))
	// +kubebuilder:scaffold:scheme

	if operatorBasePath := os.Getenv("OPERATOR_BASE_PATH"); operatorBasePath != "" {
		if info, err := os.Stat(operatorBasePath); err != nil || !info.IsDir() {
			log.Error(err, "BASE_PATH set but is invalid.Use defaultBasePath instead", "BASE_PATH", operatorBasePath)
		} else {
			defaultConfigs = operatorBasePath + "/defaultconfig"
			defaultPeerDef = operatorBasePath + "/definitions/peer"
			defaultCADef = operatorBasePath + "/definitions/ca"
			defaultOrdererDef = operatorBasePath + "/definitions/orderer"
			defaultConsoleDef = operatorBasePath + "/definitions/console"
		}
	}
}
```

**Comment by bjwswang** [comment]
@jkneubuh any suggestions ^_^ ?  btw... which operator-sdk version is this project using ? I wnat to create another new  `CRD`.

**Comment by jkneubuh** [comment]
Hi @bjwswang - Thank you very much for the great suggestions on local development.

For operator-sdk, the tools are installed by the GHA pipelines when the operator image is built: 
- https://github.com/hyperledger-labs/fabric-operator/blob/main/.github/workflows/image-build.yaml#L15
- https://github.com/hyperledger-labs/fabric-operator/blob/main/scripts/install-tools.sh#L31-L32

Looks like this is currently installing operator-sdk *1.16.0* when the image is built.  I have had success running with a more recent version at v1.24.0 on a local development workstation: 
```
% operator-sdk version 
operator-sdk version: "v1.24.0", commit: "de6a14d03de3c36dcc9de3891af788b49d15f0f3", kubernetes version: "v1.24.2", go version: "go1.19.2", GOOS: "darwin", GOARCH: "arm64"
```

**Comment by jkneubuh** [comment]
`OPERATOR_RUN_MODE` will print the zap logs as unstructured text, without the `{ "json": "formatting", "of", "logs" }` 

All set.  Happy debugging.   Thanks again @bjwswang for the great contributions moving this forward.
